### ISSUE TITLE
想根据需求，自己修改一下插件

### ISSUE THREAD

**Issue by dreamwdp** [0xlau/LiteFlowX#3]
采访一下，你是用的idea哪个版本的插件包开发的啊，我用的2021 03，一直报找不到包

**Comment by dreamwdp** [comment]
大哥，有空可以帮我看一下下面的报错嘛，编译的时候无法通过，别的一些问题都解决了，但是这个报错找半天没发现问题在哪，插件包各个版本也都是对的上的，如果您没遇到过，希望可以提供一下思路，因为本人插件开发比较小白，这个看起来像是环境gradle使用的某个类找不到，但是我用的插件版本和git上是一样的，缺的一些环境也都下完了，所以挺奇怪的

> Task :compileKotlin NO-SOURCE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :setupInstrumentCode
> Task :instrumentCode FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrumentCode'.
> taskdef class com.intellij.ant.InstrumentIdeaExtensions cannot be found
   using the classloader AntClassLoader[]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s

**Comment by Coder-XiaoYi** [comment]
JDK升级一下，建议是JDK11以上。

**Comment by dreamwdp** [comment]
查到原是1.12.0的插件依赖有问题，官方已经在13修复了
https://github.com/JetBrains/gradle-intellij-plugin/commit/f0b6ad6694ef822470d97ecc0d1d7e1c2bbd9401

**Comment by dreamwdp** [comment]
终于解决了，build.gradle加个参数 instrumentCode.set(false) 就可以过去了，本来想升到v1.13.3的，但是升了发现很多参数设置在13里面压根没有，只能靠大佬有空再看看了 kotlin语法实在是不熟悉

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by dwcooper** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
magicube101, @qiwihui, @kks-jjk, @superyzh, @minxmin, @diouf, @lzhan195, @chengshihard, @tn606024, @zzlettle, @PyVH, @hongyu315, @SAXALA, @aacjlokl, @NiBlack114, @xx10n31y, @Aweak18, @yhwoo, @doskoi, @hahatwo

**Comment by xx10n31y** [comment]
牛逼, 没subscribe的issue, 甚至没见过的repo, 都给我推送通知

**Comment by chengshihard** [comment]
> 牛逼, 没subscribe的issue, 甚至没见过的repo, 都给我推送通知

我也是。。。我都不知道这是啥
